global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # No need to open port 3030 to the HOST
  - job_name: 'modbus-prometheus-api-server'
    static_configs:
      - targets: ['host.docker.internal:3030']
