name: Rust CD

on:
  # workflow_run:
  #   workflows: ["Rust CI"]
  #   types: [completed]
  push:
    branches:
      - release
    tags:
      - '*'
  

jobs:
  build-docker-image-mac-m1:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker images
        run: |
          docker build -t modbus-prometheus-api-server:macos-m1-latest -f docker/modbus-prometheus-api-server/macOS-M1/Dockerfile .

  build-mac-m1-bin:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    container:
      image: rust:latest
    steps:
      - uses: actions/checkout@v3

      - name: Get version number from tag
        id: get_version
        run: echo "VERSION=$(git describe)" >> $GITHUB_ENV

      - name: Install Mac M1 toolchain
        run: |
          rustup target add x86_64-unknown-linux-musl
          apt -y update
          apt install -y musl-tools musl-dev gcc-x86-64-linux-gnu
          apt-get install -y build-essential libssl-dev pkg-config
          RUSTFLAGS='-C linker=x86_64-linux-gnu-gcc'
          CC='gcc'
          CC_x86_64_unknown_linux_musl=x86_64-linux-gnu-gcc
          CC_x86_64-unknown-linux-musl=x86_64-linux-gnu-gcc
      
      - name: Build Mac M1 binary
        run: cargo build --target x86_64-unknown-linux-musl --release
      
      - name: Upload Mac M1 binary
        uses: actions/upload-artifact@v2
        with:
          name: modbus-prometheus-api-server-mac-m1-${{ env.VERSION }}
          path: target/x86_64-unknown-linux-musl/release/modbus-prometheus-api-server


