name: Rust CD

on:
  push:
    branches:
      - main
    tags:
      - '*'
  
jobs:
  # build-docker-image-mac-m1:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Build Docker images
  #       run: |
  #         docker build -t modbus-prometheus-api-server:macos-m1-latest -f docker/modbus-prometheus-api-server/macOS-M1/Dockerfile .

  build-mac-m1-bin:
    runs-on: macos-latest
    container:
      image: rust:latest
    # env:
      # RUSTFLAGS: '-C linker=x86_64-linux-gnu-gcc'
      # RUSTFLAGS: '-C linker=aarch64-apple-darwin'
      # CC: 'gcc'
    #   CC_x86_64_unknown_linux_musl: x86_64-linux-gnu-gcc

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version number from tag
        id: get_version
        run: echo "VERSION=$(git describe)" >> $GITHUB_ENV

      - name: Install Mac M1 toolchain
        run: |
          rustup target add aarch64-apple-darwin
          brew install openssl@3
      
      - name: Build Mac M1 binary
        run: cargo build --target aarch64-apple-darwin --release
      
      - name: Upload Mac M1 binary
        uses: actions/upload-artifact@v2
        with:
          name: modbus-prometheus-api-server-mac-m1-${{ env.VERSION }}
          path: target/aarch64-apple-darwin/release/modbus-prometheus-api-server


