name: Rust CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and test
        run: cargo test --verbose

      - name: Generate code coverage report
        run: cargo tarpaulin --exclude-files tests/* --exclude-files src/main.rs --out Xml

