name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
  RUST_VERSION_STABLE: 1.51.0
  RUST_VERSION_NIGHTLY: nightly-2021-03-25

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION_STABLE }}
          profile: minimal
          override: true

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

