name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release
env:
  CARGO_TERM_COLOR: always
  RUST_VERSION_STABLE: 1.69.0
  RUST_VERSION_NIGHTLY: nightly-2021-03-25

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION_STABLE }}
          profile: minimal
          override: true
      
      - name: Upload test data to current runner
        run: |
          sudo mkdir -p /etc/modbus-prometheus-api-server/config/
          sudo chmod -R a+rw /etc/modbus-prometheus-api-server
          cp config/test_client.json /etc/modbus-prometheus-api-server/config/

      - name: Test
        run: cargo test

  coverage:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: create coverage directory
        run: mkdir -p coverage

      - name: Upload test data to current runner
        run: |
          sudo mkdir -p /etc/modbus-prometheus-api-server/config/
          sudo chmod -R a+rw /etc/modbus-prometheus-api-server
          cp config/test_client.json /etc/modbus-prometheus-api-server/config/
        
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION_STABLE }}
          profile: minimal
          override: true
      
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      
      - name: Run tarpaulin
        run: cargo tarpaulin --out Xml --out Lcov --output-dir ./coverage
      
      - name: Coveralls
        uses: coverallsapp/github-action@v2 
